In [31]:
import numpy as np
import pandas as pd

In [32]:
data = pd.read_csv("./ML - Assignment 2/data_logistic.txt")
data.head(2)

3.6216  8.6661  -2.8073  -0.44699  0
0  4.5459  8.1674  -2.4586  -1.46210  0
1  3.8660 -2.6383   1.9242   0.10645  0

In [33]:
features = []
targets = []
with open("./ML - Assignment 2/data_logistic.txt", 'r') as f:
    for line in f:
        arr = []
        line_arr = line.split(',')
        for i in range(len(line_arr) - 1):
            arr.append(float(line_arr[i]))
        arr.insert(0,1)
        features.append(arr)
        targets.append(int(line_arr[len(line_arr)-1]))

In [34]:
print(len(features))
print(len(targets))

1372
1372


In [35]:
# print the first 10 training examples
for i in range(10):
    print(f'TARGET:{targets[i]}  FEATURES:{features[i]}  ')

TARGET:0  FEATURES:[1, 3.6216, 8.6661, -2.8073, -0.44699]  
TARGET:0  FEATURES:[1, 4.5459, 8.1674, -2.4586, -1.4621]  
TARGET:0  FEATURES:[1, 3.866, -2.6383, 1.9242, 0.10645]  
TARGET:0  FEATURES:[1, 3.4566, 9.5228, -4.0112, -3.5944]  
TARGET:0  FEATURES:[1, 0.32924, -4.4552, 4.5718, -0.9888]  
TARGET:0  FEATURES:[1, 4.3684, 9.6718, -3.9606, -3.1625]  
TARGET:0  FEATURES:[1, 3.5912, 3.0129, 0.72888, 0.56421]  
TARGET:0  FEATURES:[1, 2.0922, -6.81, 8.4636, -0.60216]  
TARGET:0  FEATURES:[1, 3.2032, 5.7588, -0.75345, -0.61251]  
TARGET:0  FEATURES:[1, 1.5356, 9.1772, -2.2718, -0.73535]  


In [36]:
print(features[:2])
print()
print(features[0])

[[1, 3.6216, 8.6661, -2.8073, -0.44699], [1, 4.5459, 8.1674, -2.4586, -1.4621]]

[1, 3.6216, 8.6661, -2.8073, -0.44699]


In [37]:
X = np.array(features)

In [38]:
y = np.array(targets)

In [39]:
def normalize(X):
    X = X.T
    
    max_num = np.max(X, axis=1)
    min_num = np.min(X, axis=1)
    range_num = max_num - min_num
    print(max_num)
    print(min_num)
    print(range_num)
    
    for i in range(len(X)):
        if i == 0:
            continue
        X[i] = X[i] - min_num[i]
        X[i] /= range_num[i]
    
    return X.T

In [40]:
X = normalize(X)

[ 1.      6.8248 12.9516 17.9274  2.4495]
[  1.      -7.0421 -13.7731  -5.2861  -8.5482]
[ 0.     13.8669 26.7247 23.2135 10.9977]


In [41]:
print(X.shape)
print(X)

(1372, 5)
[[1.         0.76900389 0.83964273 0.10678269 0.73662766]
 [1.         0.83565902 0.82098209 0.12180412 0.64432563]
 [1.         0.78662859 0.41664827 0.31060805 0.78695091]
 ...
 [1.         0.23738543 0.01176814 0.98560321 0.52475518]
 [1.         0.25084193 0.20170105 0.76158701 0.6606745 ]
 [1.         0.32452819 0.49074676 0.34334762 0.88594888]]


In [42]:
print(X.shape)
print(y.shape)

(1372, 5)
(1372,)


In [43]:
print(X.shape[0])
print(X.shape[1])

1372
5


In [44]:
y = np.reshape(y,(y.shape[0],1))

In [45]:
print(X.shape)
print(y.shape)

(1372, 5)
(1372, 1)


In [46]:
print(y)

[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]


In [47]:
def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

In [48]:
'''
features: 1372*5
weights : 5*1
'''
def predictions(features, weights):
    '''
    returns 1D array of probabilities
    that the class is 1
    '''
    return sigmoid(np.dot(features, weights)) #this is a vector 1372*1

In [49]:
def cost_function(predictions, targets):
    cost_class1 = -targets*np.log(predictions)
    cost_class2 = -(1-targets)*np.log(1-predictions)
    cost = cost_class1 + cost_class2
    total_cost = cost.sum() / len(targets)
    return total_cost

In [50]:
'''
features: 1372*5
weights: 5*1
predictions: 1372*1
target: 1372*1

reshaped_features: 5*1372
error: 1372*1
error_value: 5*1
'''

def grad_descent(features, targets, weights, lr):
    predicted_values = predictions(features, weights)
    #reshape feature vector
    reshaped_features = np.reshape(features, (features.shape[1], features.shape[0]))
    error = predicted_values - targets
    gradient = np.dot(reshaped_features, error)
    gradient = gradient / len(features)
    # multiply by learning rate
    gradient = gradient * lr
    weights = weights - gradient 
    return weights

In [51]:
grad_descent(X,y,np.array([[1],[1],[1],[1],[1]]),0.01)

array([[0.99664128],
       [0.99668185],
       [0.99664145],
       [0.99711042],
       [0.99714304]])

In [52]:
def train(features, targets, weights, lr, iters):
    
    for i in range(iters):
        weights = grad_descent(features, targets, weights, lr)
        predicted_values = predictions(features, weights)
        cost = cost_function(predicted_values, targets)
        # print cost value every 1000 iteration
        if i % 1000 == 0:
            print("iter: "+str(i) + " cost: "+str(cost))

    return weights

In [53]:
weights = train(X,y,np.array([[0],[0],[0],[0],[0]]),0.01,15000)

iter: 0 cost: 0.6930415962737191
iter: 1000 cost: 0.6765384820983171
iter: 2000 cost: 0.6747802338884287
iter: 3000 cost: 0.6732343948586952
iter: 4000 cost: 0.67183494190053
iter: 5000 cost: 0.6705820350640767
iter: 6000 cost: 0.6694762869331242
iter: 7000 cost: 0.6685181965372945
iter: 8000 cost: 0.6677081422123271
iter: 9000 cost: 0.6670463799485997
iter: 10000 cost: 0.6665330424437135
iter: 11000 cost: 0.6661681388141842
iter: 12000 cost: 0.6659515549542998
iter: 13000 cost: 0.6658830545228844
iter: 14000 cost: 0.6659622805317347


In [54]:
print(weights)

[[-0.04972675]
 [ 0.42838136]
 [-1.34686706]
 [ 0.48993295]
 [ 0.34007464]]


In [55]:
predicted_labels = predictions(X,weights)
print(predicted_labels[:10])
print(type(predicted_labels))

[[0.36624448]
 [0.37315508]
 [0.53640537]
 [0.32753184]
 [0.53747952]
 [0.33530498]
 [0.46046006]
 [0.60286881]
 [0.40696249]
 [0.3461113 ]]
<class 'numpy.ndarray'>


In [56]:
def classify(predictions):
    print(type(predictions))
    classify_pred = []
    np.array(classify_pred)
    print(len(predictions))
    for i in range(len(predictions)):
        if (predictions[i] >= 0.5):
            classify_pred.append(1)
        else:
            classify_pred.append(0)
    return classify_pred

In [57]:
def accuracy(predicted_labels, actual_labels):
    diff = predicted_labels - actual_labels
    return 1 - (float(np.count_nonzero(diff)) / len(diff))

In [58]:
labels = classify(predicted_labels)
labels = np.reshape(labels, (1372,1))

<class 'numpy.ndarray'>
1372


In [59]:
print(labels[:10])
print(labels.shape)
print(y[:10])
print(y.shape)

[[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]]
(1372, 1)
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
(1372, 1)


In [60]:
accuracy(labels, y)

0.5575801749271136